---
- debug:
    msg: "{{aws_places | json_query('*.region') | unique}}"
    verbosity: 2

- name: Processing regions
  include_tasks: region.yml
  loop: "{{ aws_places | json_query('*.region') | unique }}"
  loop_control:
    loop_var: region

- debug:
    var: aws_image_users
