- name: "Get facts for availability zone {{ item.value.availability_zone }}"
  amazon.aws.ec2_vpc_subnet_info:
    region: "{{ item.value.region }}"
    filters:
      availability-zone: "{{ item.value.availability_zone }}"
      vpc-id: "{{ item.value.vpc_id }}"
  register: az_info
  tags: always

- name: "Fail if subnet can't be determined"
  ansible.builtin.fail:
    msg: "Subnet for availability zone {{ item.value.availability_zone }} can't be determined."
  when: az_info.subnets[0].id is not defined
  tags: always

- name: Add subnet info to place
  ansible.builtin.set_fact:
    aws_places: "{{ aws_places |
      combine({ item.key: { 'subnet_id': az_info.subnets[0].id, 'subnets': az_info.subnets } }, recursive=True) }}"
