- name: Processing inventory
  ansible.builtin.set_fact:
    ec2:
      hosts: "{{ hosts_data }}"
  vars:
    hosts_data: |-
      {% set ns = namespace() %}
      {% set ns.hosts = [] %}
      {% for group in sap_groups %}
      {% set host_data_group = {
        'gid': group.gid,
        'ec2': group.ec2 | default({}),
        'os': group.os | default({}),
        'sap': group.sap | default({})
      } %}
      {%   for host in group.hosts %}
      {%     set host_data_base = host_defaults
              | combine(host_templates[host.template], recursive=True)
              | combine(host_data_group, recursive=True)
              | combine(host, recursive=True)
              | combine({'ec2': aws_places[host.place]}, recursive=True) %}
      {%     if host.hostname is defined %}
      {%       set host_name = host.hostname %}
      {%     else %}
      {%       set host_name = hostname_prefix ~ group.gid|lower ~ '' ~ host.id %}
      {%     endif %}
      {%     set os_license = aws_image[host_data_base.ec2.image]['os_license'] | default('unknown') %}
      {%     set os_type = aws_image[host_data_base.ec2.image]['os_type'] | default('unknown') %}
      {%     set host_data_add =
                {
                  'name': host_name
                } %}
      {%     set host_data = host_data_base | combine(host_data_add, recursive=True) %}
      {%     set ns.hosts = ns.hosts + [host_data] %}
      {%   endfor %}
      {% endfor %}
      {{ ns.hosts }}

- name: Debug ec2.hosts
  ansible.builtin.debug:
    var: ec2
    verbosity: 1

- name: Set fact for all hosts names
  ansible.builtin.set_fact:
    vm_all_host_names: "{{ ec2.hosts | json_query('[*].name') }}"

- name: Debug vm_all_host_names
  ansible.builtin.debug:
    var: vm_all_host_names
    verbosity: 1
