---
- name: Show to the end user that we are using the v3 role
  ansible.builtin.debug:
    msg: |
      ----------------------------------------------------------

      Role: runsap.aws.sap_inventory_v3

      ----------------------------------------------------------

#
# Create hosts_data
#
- name: Create hosts_data / sap_inventory
  ansible.builtin.include_tasks: create_host_data.yml
#
# Create dynamic inventory
#
- name: Processing regions and add hosts to dynamic inventory
  ansible.builtin.include_tasks: region.yml
  loop: "{{ aws_places | json_query('*.region') | unique }}"
  loop_control:
    loop_var: region
