- name: "Collect aws facts for instances in region '{{ region }}'"
  amazon.aws.ec2_instance_info:
    region: "{{ region }}"
    filters: "{{ aws_inventory_filters }}"
  register: ansible_instance_facts
  check_mode: false

# - name: Debugging specific values
#   debug:
#     msg: "{{ item.tags.Name }} {{ item.tags.Host_name }} {{ lookup_host_data.ec2.image }}"
#   loop: "{{ ansible_instance_facts.instances }}"
#   loop_control:
#     label: "{{ item.tags.Name }} "
#   vars:
#     lookup_host_data: "{{ ( hostvars['localhost']['ec2']['hosts']
#       | json_query(\"[?name=='\" + item.tags.Host_name + \"']\") )[0]
#       | default({}) }}"

# - name: Debugging specific values
#   debug:
#     msg: "{{ item.tags.Name }} {{ item.tags.Host_name }} {{ os_type }} {{lookup_host_data.ec2.image}} {{ lookup_host_data.ec2.tags }}"
#   loop: "{{ ansible_instance_facts.instances }}"
#   loop_control:
#     label: "{{ item.tags.Name }} "
#   vars:
#     os_type: "{{ aws_image[lookup_host_data.ec2.image].os_type }}"
#     lookup_host_data: "{{ ( hostvars['localhost']['ec2']['hosts']
#       | json_query(\"[?name=='\" + item.tags.Host_name + \"']\") )[0]
#       | default({}) }}"


- name: Add instance to dynamic inventory
  ansible.builtin.add_host:
    hostname: "{{ item.tags.Host_name }}"

    ansible_host: "{{ item[return_address_for_ansible_host] if item.state.name == 'running' else '127.0.30.1' }}"
    ansible_user: "{{ 'sap_admin' if os_type == 'windows' else aws_tmp_user }}"
    ansible_password: "{{ winrm_password if os_type == 'windows' else '' }}"
    ansible_connection: "{{ 'winrm' if os_type == 'windows' else 'ssh' }}"
    ansible_port: "{{ '5986' if os_type == 'windows' else '22' }}"
    ansible_winrm_transport: basic
    ansible_winrm_server_cert_validation: ignore
    ansible_become_method: "{{ 'runas' if os_type == 'windows' else 'sudo' }}"

    groups:
      - "{{ aws_inventory_group }}"
      - "{{ env }}"
    region: "{{ region }}"
    ec2status: "{{ item }}"

    # host_data: per-host processed group_vars template inventory
    host_data: "{{ (hostvars['localhost']['ec2']['hosts']
      | json_query(\"[?name=='\" + item.tags.Host_name + \"']\"))[0]
      | default({}) }}"

  changed_when: false
  loop: "{{ ansible_instance_facts.instances }}"
  loop_control:
    label: "{{ item.tags.Host_name }} - {{ item.instance_id }}/{{ aws_tmp_user }}"
  vars:
    os_type: "{{ aws_image[lookup_host_data.ec2.image].os_type }}"
    lookup_host_data: "{{ (hostvars['localhost']['ec2']['hosts']
      | json_query(\"[?name=='\" + item.tags.Host_name + \"']\"))[0]
      | default({}) }}"
    aws_tmp_user: >-
        {{ aws_image[lookup_host_data.ec2.image].user }}
